# Generated by Django 4.0.1 on 2022-03-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
